name=input("Enter a name ")
place=input("Enter a place ")
animal=input("Enter an animal ")
food=input("Enter a meal ")
job=input("enter the job description ")
print("/nhere is your story:/n")
print("One day " + name + " went to " + place) 
print("He saw a " + animal + " eating some " + food)
print(name + " decided to become " + job)